### ISSUE TITLE
Complex url under Windows problem

### ISSUE THREAD

**Issue by matrixik** [toqueteos/webbrowser#1]
Try `start http://httpbin.org/get?a=1&b=2`
or `start "http://httpbin.org/get?a=1&b=2"`
Will be opened only http://httpbin.org/get?a=1 or another cmd.

To fix this you must use:
`start "%ProgramFiles%\Internet Explorer\iexplore.exe" "http://httpbin.org/get?a=1&b=2"`
with `"` around url.

Best regards

**Comment by emiddleton** [comment]
Escaped ampersands break url's under Linux Firefox.  They are not getting un-escaped.

**Comment by toqueteos** [comment]
@emiddleton Can you please write an example URL that won't work on Linux Firefox? Will test and fix asap.

**Comment by emiddleton** [comment]
@toqueteos Thanks that fixed it.
