### ISSUE TITLE
Supposed error while starting Firefox on Windows

### ISSUE THREAD

**Issue by nochso** [toqueteos/webbrowser#2]
Hi!

I tried the Windows build of something I'm writing. Firefox is opened with the correct URL, however the library seems to think that it failed. We then tried changing the default browser to IE, but it wouldn't "take" and Firefox kept opening so we couldn't rule out something related to FF.
That's also when I gave up on said machine: no dev environment..

I'm sorry I can't give more information right now, as I don't have access to a Windows machine to debug it on.

Edit: The actual error is `can't open webpage`. Here's the code I'm using: https://github.com/nochso/gomd/blob/master/gomd.go#L105 (be gentle, I'm learning ;)

**Comment by toqueteos** [comment]
Hello @nochso and thanks for contributing!

From experience I can say that this is most probably due to sloppy escaping from my side so thanks for reporting it!

To confirm the bug I only need the URL but you even provided the code so let me try reproducing the bug locally on my Windows machine and I'll send a fix ASAP.

**Comment by toqueteos** [comment]
What I did:

1. `go get -u github.com/nochso/gomd`
2. `cd $GOPATH\src\github.com\nochso\gomd`
3. Create `lorem.md` file in `D:\`

Using both `cmd.exe` and `MinGW32 shell`:

- `gomd D:\lorem.md` works, Firefox opens with URL `http://localhost:1110/edit/D%3A%5Clorem.md`
- `webbrowser.Open("http://localhost:1110/edit/D:\\lorem.md")` works, notice the double backslash

---

I need more details from your side @nochso

**Comment by nochso** [comment]
It was a simple `gomd.exe file.md`. Like I said, Firefox and the proper page open as expected. It's just that it still throws an error.

**Comment by toqueteos** [comment]
@nochso Could you please try using [wip-2016](https://github.com/toqueteos/webbrowser/tree/wip-2016) branch and see if error is still returned?

**Comment by nochso** [comment]
I'm not that familiar with the Go ecosystem yet, so I hope this did what I expect:

In `GOPATH/.../webbrowser` I ran

    git fetch
    git checkout wip-2016

Afterwards I just ran `go build` in the gomd folder. Is this a correct way?

Anyway, I'll be able to test it on the same system tomorrow.

**Comment by toqueteos** [comment]
That should work. I'll wait for confirmation, if this solves the issue I'll merge the updated branch.

**Comment by nochso** [comment]
Same as before: FF opens and an error is thrown. However the error now shows an `exit code 1`.

I'm unable to find a list of exit codes that FF might return. Then again, *is* that the exit code returned by Firefox, `cmd` or `start`?

**Comment by toqueteos** [comment]
That I don't know. I'm on Windows and calling `Open` returns a nil error.

**Comment by nochso** [comment]
I think I've only tried it with Firefox closed, not with it already open. I'll try around a bit more tomorrow.

**Comment by toqueteos** [comment]
@nochso ping?

**Comment by nochso** [comment]
Seems like this can be closed as I can't reproduce it anymore.

**Comment by toqueteos** [comment]
If you see it again please open another issue.

**Comment by nochso** [comment]
Ok, will do.
