### ISSUE TITLE
Inconsistent Blocking Behavoirs

### ISSUE THREAD

**Issue by pquerna** [toqueteos/webbrowser#4]
In the python webbrowser, it uses `os.startfile`, which "returns as soon as the associated application is launched".  Unlike the python version, if you are using `xdg-open` the `cmd.Run` waits for the process to complete, and for Chrome, xdg-open doesn't return until the Chrome process exits.  

Not sure how you want to approach this, maybe have a `func (b browserCommand) Command(s string) (*exec.Command, error)`, so then the caller can decide if they want to block with .Run() or do something else

**Comment by toqueteos** [comment]
Thanks for reaching out!

I didn't know about that detail of `xdg-open` (never got to use webbrowser on Linux 😞).
It makes sense providing that API for those in need of it, also good news is it doesn't break anything so.. consider it done!

**Aside:** I've seen some people forking the library and making minor changes to how some URL characters are escaped, has this ever been a problem to you?

**Comment by pquerna** [comment]
We haven't ran into url escaping issues, but we generally aren't opening URLs with query strings or `&` separating args, we encode everything we need into the URL, but looking at the forks, and how exec.Command works, I don't think the escaping is needed

**Comment by toqueteos** [comment]
Thanks for the feedback and for reporting the xdg-open issue!
